# Generated by Django 5.2.1 on 2025-05-17 01:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_chaldean_description_prayer_delete_prayers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prayer',
            new_name='Comment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='chaldean_description',
        ),
    ]
