# Generated by Django 5.2.1 on 2025-05-17 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_prayer_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='commenters',
            field=models.ManyToManyField(blank=True, related_name='commenters', to=settings.AUTH_USER_MODEL),
        ),
    ]
