# Generated by Django 5.2.1 on 2025-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_commenters'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ChaldeanPrayer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='EnglishPrayer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
