# Generated by Django 5.2.1 on 2025-06-07 03:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userporfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userPorfile',
            new_name='userProfile',
        ),
    ]
