# Generated by Django 5.2.1 on 2025-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_userporfile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
